/**
 * FixMyFile Supplied SVG Tool Icons Mapping
 * Maps all 49 active tool IDs to their corresponding SVG asset files
 * located in src/assets/fixmyfile-49-svg-icons/
 */

export const TOOL_SVG_MAP = {
  'jpg-to-pdf': new URL('../assets/fixmyfile-49-svg-icons/01-jpg-to-pdf.svg', import.meta.url).href,
  'pdf-to-word': new URL('../assets/fixmyfile-49-svg-icons/02-pdf-to-word.svg', import.meta.url).href,
  'pdf-to-jpg': new URL('../assets/fixmyfile-49-svg-icons/03-pdf-to-jpg.svg', import.meta.url).href,
  'word-to-pdf': new URL('../assets/fixmyfile-49-svg-icons/04-word-to-pdf.svg', import.meta.url).href,
  'merge-pdf': new URL('../assets/fixmyfile-49-svg-icons/05-merge-pdf.svg', import.meta.url).href,
  'compress-pdf': new URL('../assets/fixmyfile-49-svg-icons/06-compress-pdf.svg', import.meta.url).href,
  'split-pdf': new URL('../assets/fixmyfile-49-svg-icons/07-split-pdf.svg', import.meta.url).href,
  'pdf-to-excel': new URL('../assets/fixmyfile-49-svg-icons/08-pdf-to-excel.svg', import.meta.url).href,
  'pdf-to-powerpoint': new URL('../assets/fixmyfile-49-svg-icons/09-pdf-to-powerpoint.svg', import.meta.url).href,
  'rotate-pdf': new URL('../assets/fixmyfile-49-svg-icons/10-rotate-pdf.svg', import.meta.url).href,
  'protect-pdf': new URL('../assets/fixmyfile-49-svg-icons/11-protect-pdf.svg', import.meta.url).href,
  'unlock-pdf': new URL('../assets/fixmyfile-49-svg-icons/12-unlock-pdf.svg', import.meta.url).href,
  'pdf-to-text': new URL('../assets/fixmyfile-49-svg-icons/13-pdf-to-text.svg', import.meta.url).href,
  'extract-pdf-pages': new URL('../assets/fixmyfile-49-svg-icons/14-extract-pdf-pages.svg', import.meta.url).href,
  'delete-pdf-pages': new URL('../assets/fixmyfile-49-svg-icons/15-delete-pdf-pages.svg', import.meta.url).href,
  'reorder-pdf-pages': new URL('../assets/fixmyfile-49-svg-icons/16-reorder-pdf-pages.svg', import.meta.url).href,
  'pdf-ocr': new URL('../assets/fixmyfile-49-svg-icons/17-pdf-ocr.svg', import.meta.url).href,
  'extract-text-from-pdf': new URL('../assets/fixmyfile-49-svg-icons/18-extract-text-from-pdf.svg', import.meta.url).href,
  'background-remover': new URL('../assets/fixmyfile-49-svg-icons/19-background-remover.svg', import.meta.url).href,
  'image-compressor': new URL('../assets/fixmyfile-49-svg-icons/20-image-compressor.svg', import.meta.url).href,
  'image-resizer': new URL('../assets/fixmyfile-49-svg-icons/21-image-resizer.svg', import.meta.url).href,
  'image-converter': new URL('../assets/fixmyfile-49-svg-icons/22-image-converter.svg', import.meta.url).href,
  'jpg-to-png': new URL('../assets/fixmyfile-49-svg-icons/23-jpg-to-png.svg', import.meta.url).href,
  'png-to-jpg': new URL('../assets/fixmyfile-49-svg-icons/24-png-to-jpg.svg', import.meta.url).href,
  'heic-to-jpg': new URL('../assets/fixmyfile-49-svg-icons/25-heic-to-jpg.svg', import.meta.url).href,
  'webp-to-jpg': new URL('../assets/fixmyfile-49-svg-icons/26-webp-to-jpg.svg', import.meta.url).href,
  'jpg-to-webp': new URL('../assets/fixmyfile-49-svg-icons/27-jpg-to-webp.svg', import.meta.url).href,
  'webp-to-png': new URL('../assets/fixmyfile-49-svg-icons/28-webp-to-png.svg', import.meta.url).href,
  'image-rotate-flip': new URL('../assets/fixmyfile-49-svg-icons/29-image-rotate-flip.svg', import.meta.url).href,
  'image-watermark': new URL('../assets/fixmyfile-49-svg-icons/30-image-watermark.svg', import.meta.url).href,
  'image-to-pdf': new URL('../assets/fixmyfile-49-svg-icons/31-image-to-pdf.svg', import.meta.url).href,
  'image-upscaler': new URL('../assets/fixmyfile-49-svg-icons/32-image-upscaler.svg', import.meta.url).href,
  'image-to-base64': new URL('../assets/fixmyfile-49-svg-icons/33-image-to-base64.svg', import.meta.url).href,
  'image-to-text': new URL('../assets/fixmyfile-49-svg-icons/34-image-to-text.svg', import.meta.url).href,
  'jpg-to-text': new URL('../assets/fixmyfile-49-svg-icons/35-jpg-to-text.svg', import.meta.url).href,
  'png-to-text': new URL('../assets/fixmyfile-49-svg-icons/36-png-to-text.svg', import.meta.url).href,
  'screenshot-to-text': new URL('../assets/fixmyfile-49-svg-icons/37-screenshot-to-text.svg', import.meta.url).href,
  'image-cropper': new URL('../assets/fixmyfile-49-svg-icons/38-image-cropper.svg', import.meta.url).href,
  'qr-code-generator': new URL('../assets/fixmyfile-49-svg-icons/39-qr-code-generator.svg', import.meta.url).href,
  'barcode-generator': new URL('../assets/fixmyfile-49-svg-icons/40-barcode-generator.svg', import.meta.url).href,
  'currency-converter': new URL('../assets/fixmyfile-49-svg-icons/41-currency-converter.svg', import.meta.url).href,
  'percentage-calculator': new URL('../assets/fixmyfile-49-svg-icons/42-percentage-calculator.svg', import.meta.url).href,
  'password-generator': new URL('../assets/fixmyfile-49-svg-icons/43-password-generator.svg', import.meta.url).href,
  'word-counter': new URL('../assets/fixmyfile-49-svg-icons/44-word-counter.svg', import.meta.url).href,
  'emi-calculator': new URL('../assets/fixmyfile-49-svg-icons/45-emi-calculator.svg', import.meta.url).href,
  'mp4-to-mp3': new URL('../assets/fixmyfile-49-svg-icons/46-mp4-to-mp3.svg', import.meta.url).href,
  'video-compressor': new URL('../assets/fixmyfile-49-svg-icons/47-video-compressor.svg', import.meta.url).href,
  'video-to-gif': new URL('../assets/fixmyfile-49-svg-icons/48-video-to-gif.svg', import.meta.url).href,
  'gif-maker': new URL('../assets/fixmyfile-49-svg-icons/49-gif-maker.svg', import.meta.url).href
};
